"""change false for cr_id

Revision ID: 23c87308e38b
Revises: f715af7b54da
Create Date: 2025-10-17 14:34:03.470635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23c87308e38b'
down_revision = 'f715af7b54da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('available_from', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('time_limit_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('test_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['user_id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['class_id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('test_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('time_limit_min')
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('due_at')
        batch_op.drop_column('available_from')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
