"""Update course model with enhanced fields

Revision ID: 64182dfdeadb
Revises: c5ca8d14514d
Create Date: 2025-09-26 15:46:17.389560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64182dfdeadb'
down_revision = 'c5ca8d14514d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('target_score', mysql.SMALLINT(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='course_level_enum'), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='course_mode_enum'), nullable=True))
        batch_op.add_column(sa.Column('schedule_text', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('session_count', mysql.SMALLINT(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('total_hours', mysql.SMALLINT(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('tuition_fee', mysql.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('capacity', mysql.SMALLINT(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'RUNNING', 'CLOSED', 'ARCHIVED', name='course_status_enum'), server_default='OPEN', nullable=False))
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(unsigned=True), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('learning_path_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('campus_id', sa.String(length=10), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
        batch_op.create_unique_constraint(None, ['course_code'])
        batch_op.drop_column('course_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.drop_column('campus_id')
        batch_op.drop_column('learning_path_id')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('status')
        batch_op.drop_column('capacity')
        batch_op.drop_column('tuition_fee')
        batch_op.drop_column('total_hours')
        batch_op.drop_column('session_count')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('schedule_text')
        batch_op.drop_column('mode')
        batch_op.drop_column('level')
        batch_op.drop_column('target_score')
        batch_op.drop_column('course_code')

    # ### end Alembic commands ###
