"""add status for student and teacher

Revision ID: 7a482f39e564
Revises: 805f95f792c3
Create Date: 2025-10-27 18:20:51.884859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a482f39e564'
down_revision = '805f95f792c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sd_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tch_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('tch_status')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('sd_status')

    # ### end Alembic commands ###
