"""add cr_startlv for consult_registration_model

Revision ID: 805f95f792c3
Revises: 23c87308e38b
Create Date: 2025-10-20 14:30:51.226222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805f95f792c3'
down_revision = '23c87308e38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consult_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cr_startlv', sa.Enum('300–450', '450–600', '600–750', '750–900', name='student_levels'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consult_registration', schema=None) as batch_op:
        batch_op.drop_column('cr_startlv')

    # ### end Alembic commands ###
