"""modify att_responses_json

Revision ID: 8b0ceb2415ef
Revises: ae4f751f8003
Create Date: 2025-10-10 09:48:27.359541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b0ceb2415ef'
down_revision = 'ae4f751f8003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('att_responses_json',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=2048),
               existing_nullable=True)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('test_total_questions',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('test_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('test_status',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               existing_nullable=True)
        batch_op.alter_column('test_total_questions',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('att_responses_json',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)

    op.create_table('course',
    sa.Column('course_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('cou_course_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('course_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('course_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True),
    sa.Column('course_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('course_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.ForeignKeyConstraint(['cou_course_id'], ['course.course_id'], name=op.f('course_ibfk_1'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
