"""Modify course model

Revision ID: 8b691fac057b
Revises: 8b0ceb2415ef
Create Date: 2025-10-13 09:04:21.254305

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8b691fac057b"
down_revision = "8b0ceb2415ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Chỉ giữ lại các thay đổi liên quan đến courses
    with op.batch_alter_table("courses", schema=None) as batch_op:
        # Các thay đổi cho bảng courses ở đây
        pass

    # XÓA HOẶC COMMENT toàn bộ phần này - KHÔNG thay đổi bảng tests
    # with op.batch_alter_table('tests', schema=None) as batch_op:
    #     batch_op.alter_column('test_total_questions',
    #            existing_type=mysql.INTEGER(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    #     batch_op.alter_column('test_status',
    #            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # XÓA HOẶC COMMENT phần tests
    # with op.batch_alter_table('tests', schema=None) as batch_op:
    #     batch_op.alter_column('test_status',
    #            existing_type=sa.DateTime(),
    #            type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
    #            existing_nullable=True)
    #     batch_op.alter_column('test_total_questions',
    #            existing_type=sa.DateTime(),
    #            type_=mysql.INTEGER(),
    #            existing_nullable=True)

    # Chỉ giữ lại các thay đổi liên quan đến courses
    with op.batch_alter_table("courses", schema=None) as batch_op:
        # Reverse changes cho courses
        pass

    # ### end Alembic commands ###
