"""add status for consult_registration

Revision ID: a2cee9cacb6a
Revises: 7a482f39e564
Create Date: 2025-10-27 18:26:56.074433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cee9cacb6a'
down_revision = '7a482f39e564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consult_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cr_status', sa.String(length=20), nullable=False, comment='Trạng thái đăng ký tư vấn (pending/approved/rejected)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consult_registration', schema=None) as batch_op:
        batch_op.drop_column('cr_status')

    # ### end Alembic commands ###
