"""add cou_course_id

Revision ID: a618686ca7ad
Revises: 8b691fac057b
Create Date: 2025-10-13 09:32:41.699823

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "a618686ca7ad"
down_revision = "8b691fac057b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Kiểm tra xem cột đã tồn tại chưa
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("courses")]

    # Chỉ thêm nếu cột chưa tồn tại
    if "cou_course_id" not in columns:
        with op.batch_alter_table("courses", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "cou_course_id",
                    sa.String(length=10),
                    nullable=True,
                    comment="ID của khóa học tiên quyết (prerequisite course)",
                )
            )
            batch_op.create_foreign_key(
                "fk_courses_prerequisite",
                "courses",
                ["cou_course_id"],
                ["course_id"],
                onupdate="RESTRICT",
                ondelete="RESTRICT",
            )
            batch_op.create_check_constraint(
                "chk_course_not_self_prerequisite", "cou_course_id != course_id"
            )
    else:
        print("Column 'cou_course_id' already exists, skipping...")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Kiểm tra xem cột có tồn tại không
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("courses")]

    # Chỉ xóa nếu cột tồn tại
    if "cou_course_id" in columns:
        with op.batch_alter_table("courses", schema=None) as batch_op:
            batch_op.drop_constraint("chk_course_not_self_prerequisite", type_="check")
            batch_op.drop_constraint("fk_courses_prerequisite", type_="foreignkey")
            batch_op.drop_column("cou_course_id")
    else:
        print("Column 'cou_course_id' does not exist, skipping...")

    # ### end Alembic commands ###
