"""Modify lv for course model(enum)

Revision ID: d240edbc7955
Revises: f3b3c4dec48d
Create Date: 2025-10-15 23:34:06.122158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd240edbc7955'
down_revision = 'f3b3c4dec48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('sd_startlv',
               existing_type=mysql.ENUM('300_450', '450_600', '600_750', '750_900', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('300–450', '450–600', '600–750', '750–900', name='student_levels'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('sd_startlv',
               existing_type=sa.Enum('300–450', '450–600', '600–750', '750–900', name='student_levels'),
               type_=mysql.ENUM('300_450', '450_600', '600_750', '750_900', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
