"""Update learning path model structure

Revision ID: e5b356931161
Revises: 64182dfdeadb
Create Date: 2025-09-29 09:39:10.858962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5b356931161'
down_revision = '64182dfdeadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('course_status')

    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
        batch_op.create_index(batch_op.f('ix_learning_paths_lp_id'), ['lp_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('learning_paths_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('learning_paths_ibfk_1'), 'courses', ['course_id'], ['course_id'])
        batch_op.drop_index(batch_op.f('ix_learning_paths_lp_id'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=False))

    # ### end Alembic commands ###
