"""init

Revision ID: effa3b7ec121
Revises: 
Create Date: 2025-09-23 09:48:31.670726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effa3b7ec121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('course_status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('questions',
    sa.Column('qs_index', sa.Integer(), nullable=False),
    sa.Column('qs_desciption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('qs_index')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=50), nullable=True),
    sa.Column('room_capacity', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('room_location', sa.String(length=100), nullable=True),
    sa.Column('room_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('students',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.Column('user_gender', sa.String(length=1), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_birthday', sa.Date(), nullable=True),
    sa.Column('user_telephone', sa.String(length=15), nullable=True),
    sa.Column('sd_startlv', sa.String(length=100), nullable=True),
    sa.Column('sd_enrollmenttdate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teachers',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.Column('user_gender', sa.String(length=1), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_birthday', sa.Date(), nullable=True),
    sa.Column('user_telephone', sa.String(length=15), nullable=True),
    sa.Column('tch_specialization', sa.String(length=100), nullable=True),
    sa.Column('tch_qualification', sa.String(length=100), nullable=True),
    sa.Column('tch_hire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.Column('user_gender', sa.String(length=1), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_birthday', sa.Date(), nullable=True),
    sa.Column('user_telephone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('words',
    sa.Column('w_index', sa.Integer(), nullable=False),
    sa.Column('w_english', sa.String(length=100), nullable=True),
    sa.Column('w_vietnamese', sa.String(length=100), nullable=True),
    sa.Column('w_englishmean', sa.String(length=255), nullable=True),
    sa.Column('w_vietnamesemean', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('w_index')
    )
    op.create_table('answers',
    sa.Column('as_index', sa.Integer(), nullable=False),
    sa.Column('qs_index', sa.Integer(), nullable=False),
    sa.Column('as_true', sa.Boolean(), nullable=True),
    sa.Column('as_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['qs_index'], ['questions.qs_index'], ),
    sa.PrimaryKeyConstraint('as_index')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('class_startdate', sa.Date(), nullable=True),
    sa.Column('class_enddate', sa.Date(), nullable=True),
    sa.Column('class_maxstudents', sa.Integer(), nullable=True),
    sa.Column('class_currentenrollment', sa.Integer(), nullable=True),
    sa.Column('class_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('learning_paths',
    sa.Column('lp_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('lp_name', sa.String(length=100), nullable=True),
    sa.Column('lp_desciption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('lp_id')
    )
    op.create_table('student_words',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('w_index', sa.Integer(), nullable=False),
    sa.Column('learned_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['students.user_id'], ),
    sa.ForeignKeyConstraint(['w_index'], ['words.w_index'], ),
    sa.PrimaryKeyConstraint('user_id', 'w_index')
    )
    op.create_table('enrollments',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['students.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'class_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('schedule_startime', sa.Time(), nullable=True),
    sa.Column('schedule_endtime', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['teachers.user_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('skills',
    sa.Column('sk_id', sa.Integer(), nullable=False),
    sa.Column('lp_id', sa.Integer(), nullable=False),
    sa.Column('sk_name', sa.String(length=100), nullable=True),
    sa.Column('sk_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lp_id'], ['learning_paths.lp_id'], ),
    sa.PrimaryKeyConstraint('sk_id')
    )
    op.create_table('lessons',
    sa.Column('ls_id', sa.Integer(), nullable=False),
    sa.Column('sk_id', sa.Integer(), nullable=False),
    sa.Column('ls_name', sa.String(length=150), nullable=True),
    sa.Column('ls_link', sa.String(length=255), nullable=True),
    sa.Column('ls_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sk_id'], ['skills.sk_id'], ),
    sa.PrimaryKeyConstraint('ls_id')
    )
    op.create_table('tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('sk_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=True),
    sa.Column('test_description', sa.Text(), nullable=True),
    sa.Column('test_total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('test_passing_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('test_duration', sa.Integer(), nullable=True),
    sa.Column('test_starttime', sa.DateTime(), nullable=True),
    sa.Column('test_endtime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sk_id'], ['skills.sk_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('has_question',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('qs_index', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['qs_index'], ['questions.qs_index'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('test_id', 'qs_index')
    )
    op.create_table('scores',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('sc_score', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.ForeignKeyConstraint(['user_id', 'class_id'], ['enrollments.user_id', 'enrollments.class_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'class_id', 'test_id')
    )
    op.create_table('vocalbulary',
    sa.Column('vc_index', sa.Integer(), nullable=False),
    sa.Column('ls_id', sa.Integer(), nullable=False),
    sa.Column('vc_english', sa.String(length=100), nullable=True),
    sa.Column('vc_vietnamese', sa.String(length=100), nullable=True),
    sa.Column('vc_englishmean', sa.String(length=255), nullable=True),
    sa.Column('vc_vietnamesemean', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ls_id'], ['lessons.ls_id'], ),
    sa.PrimaryKeyConstraint('vc_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocalbulary')
    op.drop_table('scores')
    op.drop_table('has_question')
    op.drop_table('tests')
    op.drop_table('lessons')
    op.drop_table('skills')
    op.drop_table('schedules')
    op.drop_table('enrollments')
    op.drop_table('student_words')
    op.drop_table('learning_paths')
    op.drop_table('classes')
    op.drop_table('answers')
    op.drop_table('words')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('rooms')
    op.drop_table('questions')
    op.drop_table('courses')
    # ### end Alembic commands ###
