"""Modify sd_startlv for student model(enum)

Revision ID: f3b3c4dec48d
Revises: fd2223dd3cd8
Create Date: 2025-10-14 18:13:15.058580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3b3c4dec48d'
down_revision = 'fd2223dd3cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('sd_startlv',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Enum('300_450', '450_600', '600_750', '750_900', name='student_levels'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('sd_startlv',
               existing_type=sa.Enum('300_450', '450_600', '600_750', '750_900', name='student_levels'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
