"""add consult_registration_model

Revision ID: f715af7b54da
Revises: b9195d84a1e1
Create Date: 2025-10-17 09:54:39.533619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f715af7b54da'
down_revision = 'b9195d84a1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consult_registration',
    sa.Column('cr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=10), nullable=False, comment='ID của khóa học được tư vấn'),
    sa.Column('cr_fullname', sa.String(length=100), nullable=True, comment='Họ tên người đăng ký tư vấn'),
    sa.Column('cr_birthday', sa.Date(), nullable=True, comment='Ngày sinh'),
    sa.Column('cr_phone', sa.String(length=15), nullable=True, comment='Số điện thoại liên hệ'),
    sa.Column('cr_email', sa.String(length=100), nullable=True, comment='Email liên hệ'),
    sa.Column('cr_gender', sa.String(length=1), nullable=True, comment='Giới tính (M: Male, F: Female)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cr_id')
    )
    with op.batch_alter_table('consult_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consult_registration_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consult_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consult_registration_course_id'))

    op.drop_table('consult_registration')
    # ### end Alembic commands ###
