"""Remove teacher_id and learningpath_id

Revision ID: fd2223dd3cd8
Revises: a618686ca7ad
Create Date: 2025-10-13 10:06:15.077882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd2223dd3cd8'
down_revision = 'a618686ca7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('learning_path_id')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('test_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('test_status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_path_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))

    # ### end Alembic commands ###
